
MIN_NUM_PLAYERS = 4;
MAX_NUM_PLAYERS = 8;

NUM_CARDS_STARTING_ROUND = 5;
MAX_NUM_ROUNDS = 4;

module.exports = {
    MIN_NUM_PLAYERS,
    MAX_NUM_PLAYERS,
    NUM_CARDS_STARTING_ROUND,
    MAX_NUM_ROUNDS,
};
